#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv
from pathlib import Path
from collections import defaultdict, Counter
from okhotsk_common import read_ines, text_region, read_pointer_table, dictionary, TEXT_BANK_FIRST, PRG_BANK_SIZE
from stream_codec import parse_stream, decode_stream_symbolic, stream_refs_f2, stream_control_codes, collect_f2_graph


def bank_cpu(ptr: int):
    bank = TEXT_BANK_FIRST + (ptr // PRG_BANK_SIZE)
    cpu = 0x8000 + (ptr % PRG_BANK_SIZE)
    return bank, cpu


def main():
    ap=argparse.ArgumentParser(description='Stream-aware full Okhotsk FC script extractor.')
    ap.add_argument('rom')
    ap.add_argument('-o','--out',default='okhotsk_script')
    args=ap.parse_args()
    info=read_ines(args.rom); region=text_region(info); ptrs=read_pointer_table(region); d=dictionary(region,ptrs)
    out=Path(args.out); out.mkdir(parents=True,exist_ok=True)

    byptr=defaultdict(list)
    for i,p in enumerate(ptrs[2:],2):
        if p != 0xFFFF and 0 <= p < len(region): byptr[p].append(i)
    unique=sorted(byptr, key=lambda p: byptr[p][0])

    # F2 graph includes unindexed shared suffixes.
    allstreams, graph = collect_f2_graph(region, unique)
    incoming=Counter()
    for src,rr in graph.items():
        for r in rr: incoming[r]+=1

    # Strictly interior F2 targets and pointer roots make relocation risky.
    all_f2_targets=set(incoming)
    pointer_starts=set(unique)
    rows=[]; blocks=[]
    for p in unique:
        raw,ops,complete=parse_stream(region,p)
        end=p+len(raw)
        ids=byptr[p]
        controls=stream_control_codes(ops)
        refs=stream_refs_f2(ops)
        interior_refs=sorted(x for x in all_f2_targets if p < x < end)
        interior_ptrs=sorted(x for x in pointer_starts if p < x < end)
        reasons=[]
        if not complete: reasons.append('TRUNCATED')
        if interior_refs: reasons.append('F2_INTERIOR')
        if interior_ptrs: reasons.append('PTR_INTERIOR')
        reloc='YES' if not reasons else 'NO'
        cls='plain' if not [c for c in controls if c != 0xF8] else 'controlled'
        jp=decode_stream_symbolic(region,p,d,expand_f2=False)
        jpx=decode_stream_symbolic(region,p,d,expand_f2=True)
        bank,cpu=bank_cpu(p)
        rows.append([ids[0],','.join(map(str,ids)),f'{p:04X}',f'{bank:X}',f'{cpu:04X}',len(raw),cls,reloc,
                     '|'.join(reasons),incoming[p],len(refs),','.join(f'{x:04X}' for x in refs),
                     ','.join(f'{x:02X}' for x in controls),raw.hex(' ').upper(),jp.replace('\n','\\n'),jpx.replace('\n','\\n')])
        blocks.append((ids,p,raw,cls,reloc,reasons,refs,controls,jp,jpx,bank,cpu))

    with (out/'script_index.tsv').open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.writer(f,delimiter='\t')
        w.writerow(['id','ids','ptr','bank','cpu','len','class','reloc','reloc_reasons','incoming_f2','outgoing_f2','f2_targets','f_controls','raw','jp','jp_expanded'])
        w.writerows(rows)

    with (out/'script_work.txt').open('w',encoding='utf-8-sig',newline='\n') as f:
        f.write('# Hokkaidou Rensa Satsujin - Okhotsk ni Kiyu: translation work file\n')
        f.write('# Generated by v0.4 stream-aware extractor. Edit ONLY TR_BEGIN..TR_END.\n')
        f.write('# Newline = F8. Preserve symbolic [F?] controls when the JP block contains them.\n')
        f.write('# Multiple IDS means several pointer-table entries share the same physical record.\n\n')
        for ids,p,raw,cls,reloc,reasons,refs,controls,jp,jpx,bank,cpu in blocks:
            reason='-' if not reasons else ','.join(reasons)
            f.write(f'@@ ID={ids[0]:04d} IDS={",".join(f"{x:04d}" for x in ids)} PTR={p:04X} LEN={len(raw)} BANK={bank:X} CPU=${cpu:04X} CLASS={cls} RELOC={reloc} REASON={reason}\n')
            f.write('RAW='+raw.hex(' ').upper()+'\n')
            if refs: f.write('F2_REFS='+','.join(f'${x:04X}' for x in refs)+'\n')
            if controls: f.write('F_CONTROLS='+','.join(f'${x:02X}' for x in controls)+'\n')
            f.write('JP_BEGIN\n'+jp+'\nJP_END\n')
            if jpx != jp:
                f.write('JP_EXPANDED_BEGIN\n'+jpx+'\nJP_EXPANDED_END\n')
            f.write('TR_BEGIN\nTR_END\n\n')

    # Dictionary dump.
    with (out/'dictionary.tsv').open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.writer(f,delimiter='\t'); w.writerow(['token','index','raw','decoded'])
        from okhotsk_common import decode_bytes
        for i,e in enumerate(d):
            txt,_=decode_bytes(e,d,stop_at_ff=False)
            w.writerow([f'{0x60+i:02X}',i,e.hex(' ').upper(),txt.replace('\n','\\n')])

    # F2 references including unindexed shared streams.
    with (out/'f2_references.tsv').open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.writer(f,delimiter='\t'); w.writerow(['source','target','target_is_pointer_start','target_ids'])
        for src in sorted(graph):
            for target in graph[src]:
                w.writerow([f'{src:04X}',f'{target:04X}',int(target in byptr),','.join(map(str,byptr.get(target,[])))])

    # Shared F2-only streams are useful during reverse engineering even if not pointer-table roots.
    with (out/'shared_streams.tsv').open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.writer(f,delimiter='\t'); w.writerow(['ptr','len','raw','decoded','expanded'])
        for p in sorted(allstreams-pointer_starts):
            raw,ops,ok=parse_stream(region,p)
            w.writerow([f'{p:04X}',len(raw),raw.hex(' ').upper(),
                        decode_stream_symbolic(region,p,d,expand_f2=False).replace('\n','\\n'),
                        decode_stream_symbolic(region,p,d,expand_f2=True).replace('\n','\\n')])

    # ROM/layout report.
    ctr=Counter(r[6] for r in rows)
    reloc_yes=sum(1 for r in rows if r[7]=='YES')
    (out/'rom_info.txt').write_text(
        f"SHA256={info['sha256']}\nPRG_BANKS={info['prg_banks']}\nCHR_BANKS={info['chr_banks']}\nMAPPER={info['mapper']}\n"
        f"POINTER_COUNT={len(ptrs)}\nUNIQUE_SCRIPT_POINTERS={len(unique)}\nF2_REACHABLE_STREAMS={len(allstreams)}\n"
        f"F2_ONLY_SHARED_STREAMS={len(allstreams-pointer_starts)}\nDICT_ENTRIES={len(d)}\nDICT_START={ptrs[0]:04X}\nDICT_END={ptrs[1]:04X}\n"
        f"PLAIN_RECORDS={ctr['plain']}\nCONTROLLED_RECORDS={ctr['controlled']}\nCONSERVATIVE_RELOC_YES={reloc_yes}\n",
        encoding='utf-8')
    print(f'Pointer entries: {len(ptrs)}; unique script roots: {len(unique)}')
    print(f'F2 reachable streams: {len(allstreams)} ({len(allstreams-pointer_starts)} shared/non-table)')
    print(f'Conservative relocation candidates: {reloc_yes}/{len(unique)}')
    print(f'Output: {out.resolve()}')

if __name__=='__main__': main()
